# Generated by Django 5.1.3 on 2024-12-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector_Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.capitulo')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.lector')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='lector',
            field=models.ManyToManyField(through='libro.Lector_Capitulo', to='libro.lector'),
        ),
    ]
